Repository GoogleCloudPlatform/ramble, pull requests merged in 2023-10, with the labels that each got.

#275 Add a typos config file to override incorrect typos
  .github/workflows/spelling.yaml
  .typos.toml
  lib/ramble/docs/workspace.rst
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/cmd/repo.py
  lib/ramble/ramble/test/cmd/config.py
  lib/ramble/ramble/test/conftest.py
  lib/ramble/ramble/util/naming.py
  share/ramble/bash/ramble-completion.in
  share/ramble/ramble-completion.bash
  share/ramble/setup-env.fish
Labels: enhancement

#276 Add HNS-REAXFF workload to LAMMPS
  var/ramble/repos/builtin/applications/lammps/application.py
Labels: application definition

#277 Add debug info to docs, and docs link to readme
  README.md
  lib/ramble/docs/getting_started.rst
Labels: documentation

#279 Add a spack-stack application definition
  var/ramble/repos/builtin/applications/spack-stack/application.py
Labels: application definition

#271 Implement a custom format parser
  lib/ramble/ramble/application.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/test/expander.py
Labels: enhancement

#288 Fix an invalid lookup where spack variables are None
  lib/ramble/ramble/software_environments.py
Labels: bug

#292 Update the gromacs tutorial content
  lib/ramble/docs/tutorials/running_a_simple_gromacs_experiment.rst
  lib/ramble/ramble/workspace/workspace.py
Labels: documentation

#284 Allow all language features to be class methods
  lib/ramble/ramble/application.py
  lib/ramble/ramble/language/language_base.py
  lib/ramble/ramble/language/modifier_language.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/test/application_language.py
  lib/ramble/ramble/test/modifier_language.py
  lib/ramble/ramble/util/directives.py
Labels: enhancement

#293 Cleanup application developers guide
  lib/ramble/docs/dev_guides/application_dev_guide.rst
  lib/ramble/docs/workspace.rst
Labels: documentation

#294 Add documentation around `ramble info`
  lib/ramble/docs/getting_started.rst
Labels: documentation

#298 Allow the setup pipeline to skip/fail workspace inventory generation
  lib/ramble/ramble/pipeline.py
Labels: bug

#303 Allow `spack compiler find` to have flags
  lib/ramble/ramble/schema/config.py
  lib/ramble/ramble/spack_runner.py
  lib/ramble/ramble/test/spack_runner.py
Labels: enhancement

#296 Add a custom logger to ramble
  lib/ramble/ramble/appkit.py
  lib/ramble/ramble/application.py
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/cmd/__init__.py
  lib/ramble/ramble/cmd/attributes.py
  lib/ramble/ramble/cmd/clean.py
  lib/ramble/ramble/cmd/commands.py
  lib/ramble/ramble/cmd/common/__init__.py
  lib/ramble/ramble/cmd/common/list.py
  lib/ramble/ramble/cmd/config.py
  lib/ramble/ramble/cmd/edit.py
  lib/ramble/ramble/cmd/license.py
  lib/ramble/ramble/cmd/mirror.py
  lib/ramble/ramble/cmd/repo.py
  lib/ramble/ramble/cmd/results.py
  lib/ramble/ramble/cmd/unit_test.py
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/config.py
  lib/ramble/ramble/error.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/experimental/uploader.py
  lib/ramble/ramble/fetch_strategy.py
  lib/ramble/ramble/keywords.py
  lib/ramble/ramble/language/shared_language.py
  lib/ramble/ramble/main.py
  lib/ramble/ramble/mirror.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/modkit.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/renderer.py
  lib/ramble/ramble/repository.py
  lib/ramble/ramble/schema/config.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/spack_runner.py
  lib/ramble/ramble/spec.py
  lib/ramble/ramble/stage.py
  lib/ramble/ramble/success_criteria.py
  lib/ramble/ramble/test/commands.py
  lib/ramble/ramble/util/editor.py
  lib/ramble/ramble/util/executable.py
  lib/ramble/ramble/util/logger.py
  lib/ramble/ramble/util/matrices.py
  lib/ramble/ramble/util/path.py
  lib/ramble/ramble/util/web.py
  lib/ramble/ramble/workspace/workspace.py
  requirements.txt
  share/ramble/ramble-completion.bash
Labels: enhancement

#304 Define variables from modifiers before rendering templates
  lib/ramble/ramble/application.py
Labels: bug
