Repository GoogleCloudPlatform/ramble, pull requests merged in 2023-11, with the labels that each got.

#305 Add a more robust success criteria for the spack-stack application
  var/ramble/repos/builtin/applications/spack-stack/application.py
Labels: application definition

#306 Enhance error messages for spack commands
  lib/ramble/ramble/spack_runner.py
  lib/ramble/ramble/util/logger.py
Labels: enhancement

#302 Fix nested compiler install
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/test/end_to_end/nested_compilers_are_installed.py
Labels: bug

#312 Add missing import in spack-stack app definition
  var/ramble/repos/builtin/applications/spack-stack/application.py
Labels: application definition

#313 Add a hello world tutorial
  lib/ramble/docs/dev_guides/application_dev_guide.rst
  lib/ramble/docs/tutorials.rst
  lib/ramble/docs/tutorials/hello_world.rst
  lib/ramble/docs/tutorials/running_a_simple_gromacs_experiment.rst
  lib/ramble/ramble/cmd/on.py
  var/ramble/repos/builtin/applications/gromacs/application.py
  var/ramble/repos/builtin/applications/hostname/application.py
Labels: documentation, application definition

#311 Disable color characters in log files
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/util/logger.py
Labels: enhancement

#314 Add a tutorial about modifying existing experiments
  lib/ramble/docs/tutorials.rst
  lib/ramble/docs/tutorials/modifying_a_gromacs_experiment.rst
  lib/ramble/docs/tutorials/running_a_simple_gromacs_experiment.rst
  lib/ramble/docs/tutorials/shared/gromacs_workspace.rst
Labels: documentation

#319 Add psm3 modifier
  var/ramble/repos/builtin/modifiers/conditional-psm3/modifier.py
Labels: enhancement

#323 Define zips as a config section
  lib/ramble/ramble/config.py
  lib/ramble/ramble/context.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/schema/applications.py
  lib/ramble/ramble/schema/merged.py
  lib/ramble/ramble/schema/spack.py
  lib/ramble/ramble/schema/workspace.py
  lib/ramble/ramble/schema/zips.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/end_to_end/explicit_zips.py
  lib/ramble/ramble/workspace/workspace.py
Labels: enhancement

#322 Stop using "shm:tcp" as it is no longer supported
  var/ramble/repos/builtin/applications/intel-mpi-benchmarks/application.py
Labels: application definition

#324 Tutorials for zips, matrices, variable expansion and indirection, and software stack parameterization
  lib/ramble/docs/tutorials.rst
  lib/ramble/docs/tutorials/using_zips_and_matrices.rst
  lib/ramble/docs/tutorials/var_expansion_indirection_and_stack_parameterization.rst
Labels: documentation

#325 Convert GCP modifier to executable_modifier format and collect all ids
  var/ramble/repos/builtin/modifiers/gcp-metadata/modifier.py
Labels: enhancement, modifier

#326 Add three tutorials and cleanup tutorial content
  lib/ramble/docs/tutorials.rst
  lib/ramble/docs/tutorials/10_using_modifiers.rst
  lib/ramble/docs/tutorials/11_using_internals.rst
  lib/ramble/docs/tutorials/1_hello_world.rst
  lib/ramble/docs/tutorials/2_running_a_simple_gromacs_experiment.rst
  lib/ramble/docs/tutorials/3_modifying_a_gromacs_experiment.rst
  lib/ramble/docs/tutorials/4_using_vectors_and_matrices.rst
  lib/ramble/docs/tutorials/5_changing_your_software_stack.rst
  lib/ramble/docs/tutorials/6_configuring_a_scaling_study.rst
  lib/ramble/docs/tutorials/7_using_zips_and_matrices.rst
  lib/ramble/docs/tutorials/8_var_expansion_indirection_and_stack_parameterization.rst
  lib/ramble/docs/tutorials/9_success_criteria.rst
  lib/ramble/docs/tutorials/shared/gromacs_execute.rst
  lib/ramble/docs/tutorials/shared/wrf_execute.rst
  lib/ramble/docs/tutorials/shared/wrf_scaling_workspace.rst
  lib/ramble/docs/workspace_config.rst
Labels: documentation
