Repository GoogleCloudPlatform/ramble, pull requests merged in 2023-12, with the labels that each got.

#327 Allow custom executables to be injected relative to other executables
  lib/ramble/docs/configuration_files.rst
  lib/ramble/docs/tutorials/11_using_internals.rst
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/context.py
  lib/ramble/ramble/namespace.py
  lib/ramble/ramble/schema/internals.py
  lib/ramble/ramble/test/end_to_end/custom_executables.py
Labels: documentation, enhancement, testing

#336 Allow empty spack environments when constructing hash
  lib/ramble/ramble/spack_runner.py
  lib/ramble/ramble/test/workspace_hashing/unsetup_workspace_cannot_analyze.py
Labels: enhancement

#338 Add `experiment_index` as a defined variable
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/keywords.py
  lib/ramble/ramble/pipeline.py
Labels: enhancement

#341 Prevent expander from searching across new lines
  lib/ramble/ramble/expander.py
Labels: bug, enhancement

#345 Fix expander removing leading zeros
  lib/ramble/ramble/expander.py
Labels: bug, enhancement

#346 Update redirection in WRF applications
  var/ramble/repos/builtin/applications/wrfv3/application.py
  var/ramble/repos/builtin/applications/wrfv4/application.py
Labels: application definition

#342 Redirect GROMACS stderr to experiment log file
  var/ramble/repos/builtin/applications/gromacs/application.py
Labels: application definition

#348 Add backported AST logic to prevent stripping zeros
  lib/ramble/ramble/expander.py
Labels: bug

#350 Add a modifier to print when experiments begin
  var/ramble/repos/builtin/modifiers/pre-exec-print/modifier.py
Labels: modifier

#352 Revert expander fixes
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/test/expander.py
  var/ramble/repos/builtin/applications/gromacs/application.py
Labels: bug

#353 Detect when 0 rows of data would be uploaded
  lib/ramble/ramble/experimental/uploader.py
Labels: bug

#355 Convert ramble root to existing variable
  lib/ramble/docs/tutorials/1_hello_world.rst
  lib/ramble/docs/tutorials/2_running_a_simple_gromacs_experiment.rst
  lib/ramble/docs/tutorials/shared/gromacs_vector_workspace.rst
  lib/ramble/docs/tutorials/shared/gromacs_workspace.rst
Labels: documentation

#362 Detect undefined packages and print a useful error message
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/software_environment.py
Labels: bug
