Repository GoogleCloudPlatform/ramble, pull requests merged in 2023-07, with the labels that each got.

#197 Convert spack version to use git and import
  lib/ramble/ramble/main.py
  lib/ramble/ramble/spack_runner.py
Labels: bug

#198 Add WATER_EXX workload to Quantum-Espresso
  var/ramble/repos/builtin/applications/quantum-espresso/application.py
Labels: objects

#189 Add caching to get_inputs
  lib/ramble/ramble/application.py
Labels: enhancement

#203 Add documentation about generated software environments
  lib/ramble/docs/workspace.rst
  lib/ramble/docs/workspace_config.rst
Labels: documentation

#207 Raise an error when variable names contain decimals
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/test/expander.py
Labels: bug

#208 Add missing language helpers to modifier language
  lib/ramble/ramble/language/modifier_language.py
Labels: bug

#202 Add application instances as an input to executable modifiers
  lib/ramble/ramble/application.py
  lib/ramble/ramble/language/modifier_language.py
  lib/ramble/ramble/modifier.py
  var/ramble/repos/builtin/modifiers/intel-aps/modifier.py
Labels: enhancement

#209 Add a basic getting started tutorial
  lib/ramble/docs/index.rst
  lib/ramble/docs/tutorials.rst
  lib/ramble/docs/tutorials/general_usage.rst
Labels: documentation

#212 Update LAMMPS application definition
  var/ramble/repos/builtin/applications/lammps/application.py
Labels: objects

#215 Update and fix OpenFoam application definition
  var/ramble/repos/builtin/applications/openfoam/application.py
Labels: objects

#211 Add success criteria to WRF application definitions
  lib/ramble/ramble/test/end_to_end/wrfv4_dry_run.py
  var/ramble/repos/builtin/applications/wrfv3/application.py
  var/ramble/repos/builtin/applications/wrfv4/application.py
Labels: testing, objects

#216 Documentation for ramble mirror
  lib/ramble/docs/mirror-config.rst
  lib/ramble/docs/tutorials.rst
  lib/ramble/docs/tutorials/mirrors.rst
Labels: documentation

#219 Fix spack using auxiliary software when installing compilers
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/spack_runner.py
  lib/ramble/ramble/test/expander.py
Labels: bug, enhancement

#224 Fix CI Syntax errors and increase minimum coverage requirement
  share/ramble/cloud-build/ramble-pr-style.yaml
  share/ramble/cloud-build/ramble-pr-unit-tests.yaml
Labels: bug

#225 Add `expand_var_name` function to expander
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/expander.py
Labels: enhancement

#221 Add support for explicit zips
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/namespace.py
  lib/ramble/ramble/renderer.py
  lib/ramble/ramble/schema/applications.py
  lib/ramble/ramble/schema/spack.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/test/end_to_end/explicit_zips.py
  lib/ramble/ramble/test/experiment_set.py
  lib/ramble/ramble/workspace/workspace.py
Labels: documentation, enhancement, testing

#230 Add support for package manager configs, and remove spack module generation
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/language/shared_language.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/spack_runner.py
  lib/ramble/ramble/test/application_language.py
  lib/ramble/ramble/test/cmd/info.py
  lib/ramble/ramble/test/cmd/mods.py
  lib/ramble/ramble/test/end_to_end/package_manager_config.py
  lib/ramble/ramble/test/modifier_functionality/mock_modifier_spack_configs.py
  lib/ramble/ramble/test/modifier_language.py
  lib/ramble/ramble/test/spack_runner.py
  var/ramble/repos/builtin.mock/applications/zlib-configs/application.py
  var/ramble/repos/builtin.mock/modifiers/spack-mod/modifier.py
Labels: enhancement
