Repository GoogleCloudPlatform/ramble, pull requests merged in 2023-08, with the labels that each got.

#232 Add an application developer guide
  lib/ramble/docs/dev_guides.rst
  lib/ramble/docs/dev_guides/application_dev_guide.rst
  lib/ramble/docs/index.rst
  lib/ramble/docs/success_criteria.rst
  lib/ramble/docs/tutorials.rst
  lib/ramble/docs/workspace.rst
Labels: documentation

#231 Add HMMER application to Ramble
  var/ramble/repos/builtin/applications/hmmer/application.py
Labels: application definition

#233 Add support for experiment exclusions
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/namespace.py
  lib/ramble/ramble/renderer.py
  lib/ramble/ramble/schema/applications.py
  lib/ramble/ramble/schema/spack.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/end_to_end/experiment_excludes.py
  lib/ramble/ramble/test/experiment_set.py
  lib/ramble/ramble/test/software_environment.py
  lib/ramble/ramble/util/matrices.py
  lib/ramble/ramble/workspace/workspace.py
Labels: enhancement

#239 Update error message for vector length mismatch
  lib/ramble/ramble/renderer.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/test/experiment_set.py
  lib/ramble/ramble/test/software_environment.py
Labels: testing

#242 Make it so licenses are sourced from a shared file
  lib/ramble/ramble/application.py
  lib/ramble/ramble/application_types/executable.py
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/keywords.py
  lib/ramble/ramble/test/application_tests.py
  lib/ramble/ramble/test/end_to_end/experiment_excludes.py
  lib/ramble/ramble/test/end_to_end/explicit_zips.py
  lib/ramble/ramble/test/end_to_end/wrfv4_dry_run.py
  lib/ramble/ramble/test/util/env.py
  lib/ramble/ramble/util/env.py
  lib/ramble/ramble/workspace/workspace.py
Labels: enhancement

#246 Update spack installation path documentation
  lib/ramble/docs/configuration_files.rst
  lib/ramble/docs/workspace.rst
  lib/ramble/docs/workspace_config.rst
Labels: documentation

#244 Add support for phase selections
  lib/ramble/docs/workspace.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/cmd/common/arguments.py
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/test/end_to_end/phase_selection.py
  lib/ramble/ramble/workspace/workspace.py
  share/ramble/ramble-completion.bash
Labels: documentation, enhancement, testing

#243 Clean up context attribute definitions
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/context.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/test/experiment_set.py
  lib/ramble/ramble/workspace/workspace.py
Labels: enhancement

#250 Replace `spack_env` with `env_path`
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/keywords.py
  lib/ramble/ramble/test/data/results_upload/test3_malformed_json.json
  lib/ramble/ramble/test/experiment_set.py
Labels: documentation, testing

#247 Add documentation around configuration scope merging
  lib/ramble/docs/configuration_files.rst
Labels: documentation

#251 Fix matrix handling
  lib/ramble/ramble/context.py
  lib/ramble/ramble/test/experiment_set.py
Labels: bug

#252 Allow compilers to be found before trying to install
  lib/ramble/ramble/spack_runner.py
Labels: bug, enhancement

#254 Fix a typo in the name of concretizer
  lib/ramble/ramble/spack_runner.py
Labels: bug
