Repository GoogleCloudPlatform/ramble, pull requests merged in 2024-10, with the labels that each got.

#672 Disable explicit testing of ramble directives
  lib/ramble/ramble/test/application_language.py
Labels: testing

#674 Update used variable tracking
  lib/ramble/ramble/application.py
  lib/ramble/ramble/language/application_language.py
  lib/ramble/ramble/language/modifier_language.py
  lib/ramble/ramble/workload.py
Labels: bug, enhancement

#677 If FOMs are None, float() raises a TypeError
  lib/ramble/ramble/application.py
Labels: bug

#675 Add NCCL_TESTS_SPLIT_MASK to nccl-tests application
  var/ramble/repos/builtin/applications/nccl-tests/application.py
Labels: application definition

#680 Defer command expansion and fix used variable tracking
  lib/ramble/ramble/application.py
Labels: bug, enhancement

#679 Quote escape wildcard in tutorial
  lib/ramble/docs/tutorials/1_hello_world.rst
Labels: documentation

#673 Add a command runner utility class
  lib/ramble/ramble/appkit.py
  lib/ramble/ramble/modkit.py
  lib/ramble/ramble/pkgmankit.py
  lib/ramble/ramble/test/end_to_end/package_manager_requirements.py
  lib/ramble/ramble/test/end_to_end/spack_env_cache.py
  lib/ramble/ramble/util/command_runner.py
  var/ramble/repos/builtin/package_managers/spack-lightweight/package_manager.py
  var/ramble/repos/builtin/package_managers/spack-lightweight/test/spack_runner.py
  var/ramble/repos/builtin/package_managers/spack/package_manager.py
Labels: enhancement

#681 Enable variable modifications to layer changes on the same variable
  lib/ramble/ramble/application.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/test/modifier_functionality/mock_layered_modifications.py
  var/ramble/repos/builtin.mock/modifiers/test-mod-2/modifier.py
  var/ramble/repos/builtin.mock/modifiers/test-mod/modifier.py
  var/ramble/repos/builtin/modifiers/intel-aps/modifier.py
Labels: bug, enhancement

#682 Ensure ssh is used when executing pdsh commands
  var/ramble/repos/builtin/modifiers/gcp-metadata/modifier.py
  var/ramble/repos/builtin/modifiers/tuned-adm/modifier.py
Labels: bug, enhancement

#686 Allow force writing workspace config files
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/workspace/workspace.py
Labels: bug

#687 Add level name to annotate the level number
  var/ramble/repos/builtin/modifiers/gcp-metadata/modifier.py
Labels: enhancement

#689 Remove new lines when defining path variables for spack
  var/ramble/repos/builtin/package_managers/spack-lightweight/package_manager.py
Labels: bug

#683 Add a pyxis-enroot modifier
  lib/ramble/ramble/util/command_runner.py
  var/ramble/repos/builtin/modifiers/pyxis-enroot/modifier.py
Labels: modifier

#690 Add a status-markers modifier
  var/ramble/repos/builtin/modifiers/status-markers/modifier.py
Labels: enhancement, modifier

#696 Remove long_print methods from base object classes
  lib/ramble/ramble/application.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/package_manager.py
Labels: cleanup

#700 Update the error message when no valid editor is found
  lib/ramble/ramble/cmd/config.py
  lib/ramble/ramble/cmd/edit.py
  lib/ramble/ramble/cmd/workspace.py
Labels: cleanup

#701 Fix experiment and workspace inventories and hashes
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/test/end_to_end/experiment_hashes.py
  var/ramble/repos/builtin/package_managers/environment-modules/package_manager.py
Labels: bug

#705 Allow modifiers to add attributes into experiment inventories
  lib/ramble/ramble/application.py
  lib/ramble/ramble/modifier.py
  var/ramble/repos/builtin/modifiers/pyxis-enroot/modifier.py
Labels: enhancement

#695 Allow `workspace concretize` to be additive
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/test/cmd/workspace_concretize.py
  lib/ramble/ramble/workspace/workspace.py
  share/ramble/ramble-completion.bash
Labels: enhancement

#691 Front-end commands for managing software
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/test/end_to_end/manage_software.py
  lib/ramble/ramble/util/conversions.py
  lib/ramble/ramble/workspace/workspace.py
  share/ramble/ramble-completion.bash
Labels: enhancement

#707 Clean up docstrings on language directives
  lib/ramble/ramble/language/application_language.py
  lib/ramble/ramble/language/modifier_language.py
  lib/ramble/ramble/language/shared_language.py
Labels: documentation

#709 Update LAMMPS figures of merit
  var/ramble/repos/builtin/applications/lammps/application.py
Labels: application definition

#708 Remove unneeded quotes from example configs
  examples/basic_expansion_config.yaml
  examples/basic_gromacs_config.yaml
  examples/basic_hostname_config.yaml
  examples/full_expansion_config.yaml
  examples/gromacs_eessi_config.yaml
  examples/tutorial_11_exec_injection_config.yaml
  examples/tutorial_11_exec_order_config.yaml
  examples/tutorial_11_new_exec_config.yaml
  examples/tutorial_1_config.yaml
  examples/tutorial_7_base_config.yaml
  examples/tutorial_7_final_config.yaml
  examples/tutorial_7_matrix_config.yaml
  examples/tutorial_8_base_config.yaml
  examples/tutorial_8_expansion_indirection_config.yaml
  examples/tutorial_8_mpi_config.yaml
  examples/tutorial_8_mpi_matrix_config.yaml
  examples/tutorial_8_software_environments_config.yaml
  examples/tutorial_9_fom_criteria_config.yaml
  examples/tutorial_9_regex_criteria_config.yaml
  examples/vector_gromacs_software_config.yaml
  examples/vector_matrix_gromacs_config.yaml
Labels: documentation

#706 Allow spack-stack to define external packages that should be automatically detected
  var/ramble/repos/builtin/applications/spack-stack/application.py
Labels: enhancement, application definition

#710 Remove directive based language tests
  lib/ramble/ramble/appkit.py
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/modifier_types/spack.py
  lib/ramble/ramble/modkit.py
  lib/ramble/ramble/test/application_language.py
  lib/ramble/ramble/test/modifier_language.py
  lib/ramble/ramble/test/package_manager_language.py
Labels: testing

#715 Update configuration precedence documentation
  lib/ramble/docs/configuration_files.rst
  lib/ramble/ramble/test/cmd/config.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/workspace/__init__.py
  lib/ramble/ramble/workspace/workspace.py
Labels: documentation

#712 Expand deployment arguments and clean URLs
  lib/ramble/docs/workspace.rst
  lib/ramble/ramble/cmd/deployment.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/test/util/path.py
  lib/ramble/ramble/util/path.py
Labels: documentation, enhancement

#704 Add separator functionality to variable modification directives
  lib/ramble/ramble/language/modifier_language.py
  lib/ramble/ramble/modifier.py
  var/ramble/repos/builtin.mock/modifiers/test-mod-2/modifier.py
  var/ramble/repos/builtin.mock/modifiers/test-mod/modifier.py
  var/ramble/repos/builtin/modifiers/intel-aps/modifier.py
  var/ramble/repos/builtin/modifiers/pyxis-enroot/modifier.py
Labels: enhancement

#711 Add metadata tracking to workspace object
  lib/ramble/ramble/namespace.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/test/workspace_hashing/workspace_name_does_not_change_hash.py
  lib/ramble/ramble/workspace/__init__.py
  lib/ramble/ramble/workspace/workspace.py
Labels: enhancement

#727 Remove an unneed print
  lib/ramble/ramble/cmd/workspace.py
Labels: cleanup

#720 Add a `disabled` mode to all modifier definitions
  lib/ramble/docs/configuration_files.rst
  lib/ramble/docs/dev_guides/modifier_dev_guide.rst
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/language/modifier_language.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/modifier_types/basic.py
  lib/ramble/ramble/modifier_types/disabled.py
  lib/ramble/ramble/test/modifier_functionality/mock_modifier_dry_run.py
  lib/ramble/ramble/test/modifier_functionality/modifier_helpers.py
  var/ramble/repos/builtin/modifiers/pyxis-enroot/modifier.py
Labels: documentation, enhancement, testing, modifier

#726 Fix an issue with the `target_dir` arg on input files
  lib/ramble/ramble/application.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/language/application_language.py
  lib/ramble/ramble/test/application_language.py
  lib/ramble/ramble/test/application_tests.py
Labels: bug, enhancement

#703 Allow package managers to have their own sub-directories under a workspace's software dir
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/package_manager.py
  lib/ramble/ramble/test/end_to_end/dryrun_copies_external_env.py
  lib/ramble/ramble/test/end_to_end/experiment_excludes.py
  lib/ramble/ramble/test/end_to_end/experiment_hashes.py
  lib/ramble/ramble/test/end_to_end/experiment_repeats.py
  lib/ramble/ramble/test/end_to_end/explicit_zips.py
  lib/ramble/ramble/test/end_to_end/included_configuration_files.py
  lib/ramble/ramble/test/end_to_end/package_manager_config.py
  lib/ramble/ramble/test/end_to_end/package_manager_requirements.py
  lib/ramble/ramble/test/end_to_end/package_manager_unique_env_dirs.py
  lib/ramble/ramble/test/end_to_end/spack_env_cache.py
  lib/ramble/ramble/test/end_to_end/test_configvar_dry_run.py
  lib/ramble/ramble/test/end_to_end/wrfv4_dry_run.py
  lib/ramble/ramble/test/modifier_application.py
  lib/ramble/ramble/test/modifier_functionality/mock_env_var_modifiers.py
  lib/ramble/ramble/test/modifier_functionality/mock_modifier_spack_configs.py
  lib/ramble/ramble/test/modifier_functionality/mock_spack_modifier.py
  lib/ramble/ramble/test/modifier_functionality/multi_modifier_dry_run.py
  lib/ramble/ramble/test/modifier_functionality/single_modifier_dry_run.py
Labels: bug, enhancement

#737 Allow `workspace info` to filter software displayed to only parts that are used by experiments
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/workspace/workspace.py
  share/ramble/ramble-completion.bash
Labels: enhancement
