Repository GoogleCloudPlatform/ramble, pull requests merged in 2024-03, with the labels that each got.

#427 Add support for modifiers to register phases
  lib/ramble/ramble/application.py
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/cmd/on.py
  lib/ramble/ramble/language/shared_language.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/test/modifier_functionality/mock_modifier_phases.py
  share/ramble/ramble-completion.bash
  var/ramble/repos/builtin.mock/modifiers/mod-phase/modifier.py
  var/ramble/repos/builtin/applications/hpcg/application.py
  var/ramble/repos/builtin/applications/hpl/application.py
  var/ramble/repos/builtin/applications/intel-hpl/application.py
  var/ramble/repos/builtin/applications/lulesh/application.py
  var/ramble/repos/builtin/applications/minixyce/application.py
  var/ramble/repos/builtin/applications/namd/application.py
  var/ramble/repos/builtin/applications/spack-stack/application.py
  var/ramble/repos/builtin/applications/wrfv3/application.py
  var/ramble/repos/builtin/applications/wrfv4/application.py
Labels: enhancement, testing

#430 Fix object usage from modifier builtins
  lib/ramble/ramble/application.py
  lib/ramble/ramble/graphs.py
  lib/ramble/ramble/language/shared_language.py
  var/ramble/repos/builtin.mock/modifiers/test-mod/modifier.py
Labels: bug, testing

#432 Update CI Image Dockerfile to use Pip for deps
  share/ramble/cloud-build/Dockerfile-centos7
Labels: testing

#431 Fix propagation of non expandable variables from modifiers
  lib/ramble/ramble/application.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/test/expander.py
  lib/ramble/ramble/test/modifier_functionality/modifier_helpers.py
  var/ramble/repos/builtin.mock/modifiers/set-env-var-mod/modifier.py
Labels: bug, testing

#433 Convert environment generation logic to lazy / implcit instead of explicit
  lib/ramble/docs/configuration_files.rst
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/test/software_environment.py
  lib/ramble/ramble/util/colors.py
Labels: documentation, enhancement, testing

#435 Fix issues with package name rendering and empty string packages in environments
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/software_environment.py
Labels: bug, testing

#434 Add a deployment command and publish pipeline
  lib/ramble/docs/workspace.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/cmd/deployment.py
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/spack_runner.py
  lib/ramble/ramble/workspace/workspace.py
  share/ramble/ramble-completion.bash
Labels: enhancement

#439 Implicitly ignore unused variables within experiment definitions
  lib/ramble/ramble/application.py
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/keywords.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/renderer.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/experiment_set.py
  lib/ramble/ramble/workspace/workspace.py
  var/ramble/repos/builtin.mock/applications/expanded_foms/application.py
Labels: enhancement, testing
