Repository GoogleCloudPlatform/ramble, pull requests merged in 2024-08, with the labels that each got.

#589 Update the info command to be more flexible
  lib/ramble/docs/tutorials/11_using_internals.rst
  lib/ramble/docs/tutorials/2_running_a_simple_gromacs_experiment.rst
  lib/ramble/docs/tutorials/3_modifying_a_gromacs_experiment.rst
  lib/ramble/docs/tutorials/6_configuring_a_scaling_study.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/cmd/common/info.py
  lib/ramble/ramble/language/application_language.py
  lib/ramble/ramble/language/modifier_language.py
  lib/ramble/ramble/test/cmd/info.py
  lib/ramble/ramble/test/cmd/mods.py
  lib/ramble/ramble/test/conftest.py
  lib/ramble/ramble/test/end_to_end/known_applications.py
  lib/ramble/ramble/util/executable.py
  lib/ramble/ramble/workload.py
  share/ramble/ramble-completion.bash
Labels: enhancement

#609 Fix spack push_to_cache phase
  var/ramble/repos/builtin/package_managers/spack-lightweight/package_manager.py
Labels: bug

#614 Collect project number in gcp-metadata
  var/ramble/repos/builtin/modifiers/gcp-metadata/modifier.py
Labels: modifier

#617 Update the unit-test timeout to 1 hour
  share/ramble/cloud-build/ramble-pr-unit-tests.yaml
Labels: testing

#615 Fix variable tracking with software environment rendering
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/software_environments.py
Labels: bug

#619 Update locking semantics for applications and workspaces
  lib/ramble/ramble/application.py
  lib/ramble/ramble/workspace/workspace.py
Labels: enhancement
