Repository GoogleCloudPlatform/ramble, pull requests merged in 2024-01, with the labels that each got.

#363 Promote `on` to a proper pipeline
  lib/ramble/docs/workspace.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/cmd/on.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/test/cmd/on.py
  lib/ramble/ramble/workspace/workspace.py
  share/ramble/ramble-completion.bash
Labels: documentation, enhancement, testing

#365 Expand args when calling executors
  lib/ramble/ramble/pipeline.py
Labels: bug

#366 Add archival to log files within workspaces
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/workspace/__init__.py
Labels: enhancement

#368 Print figures of merit for with `ramble info`
  lib/ramble/ramble/application.py
Labels: enhancement

#370 Add elk application definition
  var/ramble/repos/builtin/applications/elk/application.py
Labels: application definition

#372 Remove $ symbol from gromacs executable def
  var/ramble/repos/builtin/applications/gromacs/application.py
Labels: bug, application definition

#373 Add `expandable` attribute to variable definitions
  lib/ramble/ramble/application.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/language/application_language.py
  lib/ramble/ramble/test/end_to_end/gromacs_size_expansion.py
  lib/ramble/ramble/test/expander.py
  lib/ramble/ramble/test/mirror_tests.py
  var/ramble/repos/builtin/applications/gromacs/application.py
Labels: bug, enhancement

#374 Fix exclusion examples not rendering properly
  lib/ramble/docs/workspace_config.rst
Labels: documentation

#364 Add ramble-python command
  lib/ramble/ramble/cmd/python.py
  lib/ramble/ramble/test/cmd/python.py
  share/ramble/ramble-completion.bash
Labels: enhancement

#377 Allow fom and success criteria regular expressions to have variables
  lib/ramble/ramble/application.py
Labels: enhancement

#380 Extend accepted functions in expander AST
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/test/expander.py
Labels: enhancement

#384 Add a `sleep` application definition
  lib/ramble/ramble/expander.py
  var/ramble/repos/builtin/applications/sleep/application.py
Labels: enhancement, application definition

#383 Remove `run_experiments` from workspace.py
  lib/ramble/ramble/test/cmd/on.py
  lib/ramble/ramble/workspace/workspace.py
Labels: cleanup

#385 Add support for chained experiment variable inheritance
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/namespace.py
  lib/ramble/ramble/schema/applications.py
  lib/ramble/ramble/test/end_to_end/chained_experiment_var_inheritance.py
Labels: documentation, enhancement, testing

#382 Add notes about expected errors
  lib/ramble/docs/tutorials/10_using_modifiers.rst
  lib/ramble/docs/tutorials/4_using_vectors_and_matrices.rst
  lib/ramble/docs/tutorials/6_configuring_a_scaling_study.rst
  lib/ramble/docs/tutorials/7_using_zips_and_matrices.rst
  lib/ramble/docs/tutorials/8_var_expansion_indirection_and_stack_parameterization.rst
Labels: documentation

#389 Add support for including and excluding secrets (licenses) from workspace archives
  lib/ramble/ramble/application.py
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/workspace/__init__.py
  share/ramble/ramble-completion.bash
Labels: enhancement

#388 Change spack hash semantics to hash yaml contents
  lib/ramble/ramble/application.py
  lib/ramble/ramble/application_types/spack.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/spack_runner.py
  lib/ramble/ramble/test/workspace_hashing/unsetup_workspace_cannot_analyze.py
Labels: bug

#390 Define simplified namespace variables, and a `simplify_str` expansion function
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/experiment_set.py
  lib/ramble/ramble/keywords.py
  lib/ramble/ramble/test/expander.py
Labels: documentation, enhancement, testing

#393 Allow workspace create to create links to external directories
  lib/ramble/docs/workspace.rst
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/test/cmd/workspace.py
  lib/ramble/ramble/workspace/workspace.py
  share/ramble/ramble-completion.bash
Labels: documentation, enhancement, testing

#394 encourage compatible urllib3 version for python3.6
  requirements.txt
Labels: enhancement

#395 Fix typo `urlib` --> `urllib`
  requirements.txt
Labels: bug

#392 Allow executable scoped variable definitions
  lib/ramble/docs/workspace_config.rst
  lib/ramble/ramble/application.py
  lib/ramble/ramble/language/application_language.py
  lib/ramble/ramble/schema/internals.py
  lib/ramble/ramble/test/end_to_end/custom_executables.py
  lib/ramble/ramble/util/executable.py
Labels: documentation, enhancement, testing
