Repository GoogleCloudPlatform/ramble, pull requests merged in 2025-01, with the labels that each got.

#809 Update variable modifications with separators
  var/ramble/repos/builtin/modifiers/apptainer/modifier.py
  var/ramble/repos/builtin/modifiers/pyxis-enroot/modifier.py
Labels: modifier, cleanup

#810 Abstract HPCG and add NVIDIA-HPCG
  var/ramble/repos/builtin/applications/hpcg/application.py
  var/ramble/repos/builtin/applications/nvidia-hpcg/application.py
  var/ramble/repos/builtin/base_applications/hpcg/base_application.py
Labels: application definition

#815 Fix relative log paths in FOM and success criteria definitions
  lib/ramble/ramble/application.py
  lib/ramble/ramble/test/end_to_end/fom_log_file_path.py
  var/ramble/repos/builtin.mock/applications/fom-log-path/application.py
Labels: bug

#816 Convert HPL input generation to use template directive
  var/ramble/repos/builtin/base_applications/hpl/HPL.dat.tpl
  var/ramble/repos/builtin/base_applications/hpl/base_application.py
Labels: cleanup

#814 Add the ability to define template-specific extra variables
  lib/ramble/ramble/application.py
  lib/ramble/ramble/language/shared_language.py
  lib/ramble/ramble/test/end_to_end/test_template.py
  var/ramble/repos/builtin.mock/applications/template/application.py
  var/ramble/repos/builtin.mock/applications/template/bar.tpl
Labels: enhancement

#789 Add a slurm workflow manager
  etc/ramble/defaults/base_workflow_manager_repos.yaml
  etc/ramble/defaults/workflow_manager_repos.yaml
  lib/ramble/ramble/application.py
  lib/ramble/ramble/cmd/common/info.py
  lib/ramble/ramble/cmd/style.py
  lib/ramble/ramble/config.py
  lib/ramble/ramble/language/language_base.py
  lib/ramble/ramble/language/workflow_manager_language.py
  lib/ramble/ramble/namespace.py
  lib/ramble/ramble/repository.py
  lib/ramble/ramble/schema/base_workflow_manager_repos.py
  lib/ramble/ramble/schema/workflow_manager_repos.py
  lib/ramble/ramble/test/conftest.py
  lib/ramble/ramble/test/data/config/base_workflow_manager_repos.yaml
  lib/ramble/ramble/test/data/config/workflow_manager_repos.yaml
  lib/ramble/ramble/test/workflow_manager_functionality/slurm_workflow_manager.py
  lib/ramble/ramble/wmkit.py
  lib/ramble/ramble/workflow_manager.py
  share/ramble/ramble-completion.bash
  var/ramble/repos/builtin/base_workflow_managers/.gitignore
  var/ramble/repos/builtin/workflow_managers/slurm/batch_cancel.tpl
  var/ramble/repos/builtin/workflow_managers/slurm/batch_query.tpl
  var/ramble/repos/builtin/workflow_managers/slurm/batch_submit.tpl
  var/ramble/repos/builtin/workflow_managers/slurm/slurm_execute_experiment.tpl
  var/ramble/repos/builtin/workflow_managers/slurm/workflow_manager.py
Labels: enhancement

#822 Fix double/single colon regex for py-nemo
  var/ramble/repos/builtin/applications/py-nemo/application.py
Labels: bug, application definition

#826 Allow templates registered into other workspace paths
  lib/ramble/ramble/application.py
  lib/ramble/ramble/test/end_to_end/test_template.py
  var/ramble/repos/builtin.mock/applications/template/application.py
  var/ramble/repos/builtin.mock/applications/template/script.sh
Labels: enhancement

#832 Fix path to hpl-mxp script
  var/ramble/repos/builtin/applications/nvidia-hpl-mxp/application.py
Labels: bug, application definition

#824 Abstract container modifiers, and define a docker modifier
  var/ramble/repos/builtin/base_modifiers/container-base/base_modifier.py
  var/ramble/repos/builtin/modifiers/apptainer/modifier.py
  var/ramble/repos/builtin/modifiers/docker/modifier.py
  var/ramble/repos/builtin/modifiers/pyxis-enroot/modifier.py
Labels: enhancement, modifier

#835 Clean up use of mutable defaults under lib/ramble/ramble
  lib/ramble/ramble/application.py
  lib/ramble/ramble/cmd/commands.py
  lib/ramble/ramble/cmd/mirror.py
  lib/ramble/ramble/expander.py
  lib/ramble/ramble/filters.py
  lib/ramble/ramble/graphs.py
  lib/ramble/ramble/keywords.py
  lib/ramble/ramble/language/application_language.py
  lib/ramble/ramble/language/shared_language.py
  lib/ramble/ramble/mirror.py
  lib/ramble/ramble/modifier.py
  lib/ramble/ramble/pipeline.py
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/test/cmd/config.py
  lib/ramble/ramble/test/stage.py
  lib/ramble/ramble/util/executable.py
  lib/ramble/ramble/util/logger.py
  lib/ramble/ramble/util/path.py
  lib/ramble/ramble/workload.py
  lib/ramble/ramble/workspace/workspace.py
Labels: cleanup

#838 Ensure package conflicts are printed correctly
  lib/ramble/ramble/software_environments.py
  lib/ramble/ramble/util/colors.py
Labels: bug

#836 Clean up NVIDIA HPC Benchmark application definitions
  var/ramble/repos/builtin/applications/nvidia-hpcg/application.py
  var/ramble/repos/builtin/applications/nvidia-hpl-mxp/application.py
  var/ramble/repos/builtin/applications/nvidia-hpl/application.py
  var/ramble/repos/builtin/base_applications/nvidia-hpc-benchmarks/base_application.py
Labels: enhancement, application definition, cleanup

#843 Fix some incorrect defaults in nvidia-hpl
  var/ramble/repos/builtin/applications/nvidia-hpl/application.py
Labels: bug

#847 Add application definition for Cosmoflow
  var/ramble/repos/builtin/applications/py-cosmoflow/application.py
Labels: enhancement, application definition

#848 Update workflow managers to have an execution banner
  lib/ramble/ramble/application.py
  lib/ramble/ramble/language/language_base.py
  lib/ramble/ramble/repository.py
  lib/ramble/ramble/workflow_manager.py
  lib/ramble/ramble/workspace/workspace.py
  var/ramble/repos/builtin/workflow_managers/slurm/slurm_experiment_sbatch.tpl
  var/ramble/repos/builtin/workflow_managers/slurm/workflow_manager.py
Labels: enhancement

#852 Removing an unneeded print
  lib/ramble/ramble/repository.py
Labels: cleanup

#849 Improve error messages when pulling invalid / incomplete deployments
  lib/ramble/ramble/cmd/deployment.py
Labels: cleanup

#856 Add target information to spack software output
  var/ramble/repos/builtin/package_managers/spack-lightweight/package_manager.py
Labels: enhancement

#853 Front-end commands for managing workspace includes.
  lib/ramble/ramble/cmd/workspace.py
  lib/ramble/ramble/namespace.py
  lib/ramble/ramble/test/end_to_end/workspace_includes.py
  lib/ramble/ramble/workspace/workspace.py
  share/ramble/ramble-completion.bash
Labels: enhancement
